package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/eventhub/gateway/internal/graph/model"
	"github.com/eventhub/gateway/pkg/auth"
	eventv1 "github.com/eventhub/proto/gen/event/v1"
	ticketv1 "github.com/eventhub/proto/gen/ticket/v1"
	userv1 "github.com/eventhub/proto/gen/user/v1"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.Clients.User.CreateUser(ctx, &userv1.CreateUserRequest{
		Email:    input.Email,
		Name:     input.Name,
		Password: input.Password,
		Role:     "user",
	})
	if err != nil {
		return nil, grpcError(err)
	}
	user := mapUser(resp.GetUser())
	token, err := r.JWT.Generate(user.ID, user.Email, user.Role)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, User: user}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	resp, err := r.Clients.User.ValidateCredentials(ctx, &userv1.ValidateCredentialsRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, grpcError(err)
	}
	if !resp.GetValid() {
		return nil, gqlerror.Errorf("invalid email or password")
	}
	user := mapUser(resp.GetUser())
	token, err := r.JWT.Generate(user.ID, user.Email, user.Role)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, User: user}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("authentication required")
	}
	resp, err := r.Clients.User.UpdateProfile(ctx, &userv1.UpdateProfileRequest{
		Id:   claims.UserID,
		Name: input.Name,
	})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapUser(resp.GetUser()), nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("authentication required")
	}
	resp, err := r.Clients.Event.CreateEvent(ctx, &eventv1.CreateEventRequest{
		Title:       input.Title,
		Description: input.Description,
		Location:    input.Location,
		StartTime:   input.StartTime,
		EndTime:     input.EndTime,
		Capacity:    int32(input.Capacity),
		CreatedBy:   claims.UserID,
	})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapEvent(resp.GetEvent()), nil
}

// CancelEvent is the resolver for the cancelEvent field.
func (r *mutationResolver) CancelEvent(ctx context.Context, id string) (*model.Event, error) {
	resp, err := r.Clients.Event.CancelEvent(ctx, &eventv1.CancelEventRequest{Id: id})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapEvent(resp.GetEvent()), nil
}

// BookTicket is the resolver for the bookTicket field.
func (r *mutationResolver) BookTicket(ctx context.Context, eventID string) (*model.Ticket, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("authentication required")
	}
	resp, err := r.Clients.Ticket.CreateTicket(ctx, &ticketv1.CreateTicketRequest{
		UserId:  claims.UserID,
		EventId: eventID,
	})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapTicket(resp.GetTicket()), nil
}

// CancelTicket is the resolver for the cancelTicket field.
func (r *mutationResolver) CancelTicket(ctx context.Context, ticketID string) (*model.Ticket, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("authentication required")
	}
	resp, err := r.Clients.Ticket.CancelTicket(ctx, &ticketv1.CancelTicketRequest{
		Id:     ticketID,
		UserId: claims.UserID,
	})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapTicket(resp.GetTicket()), nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	resp, err := r.Clients.User.ListUsers(ctx, &userv1.ListUsersRequest{})
	if err != nil {
		return nil, grpcError(err)
	}
	users := make([]*model.User, 0, len(resp.GetUsers()))
	for _, u := range resp.GetUsers() {
		users = append(users, mapUser(u))
	}
	return users, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.Clients.User.GetUser(ctx, &userv1.GetUserRequest{Id: id})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapUser(resp.GetUser()), nil
}

// GetEvent is the resolver for the getEvent field.
func (r *queryResolver) GetEvent(ctx context.Context, id string) (*model.Event, error) {
	resp, err := r.Clients.Event.GetEvent(ctx, &eventv1.GetEventRequest{Id: id})
	if err != nil {
		return nil, grpcError(err)
	}
	return mapEvent(resp.GetEvent()), nil
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context, page *int, pageSize *int, search *string, location *string, status *string) (*model.EventPage, error) {
	req := &eventv1.ListEventsRequest{
		Page:     int32(derefInt(page, 1)),
		PageSize: int32(derefInt(pageSize, 20)),
		Search:   derefString(search),
		Location: derefString(location),
		Status:   derefString(status),
	}
	resp, err := r.Clients.Event.ListEvents(ctx, req)
	if err != nil {
		return nil, grpcError(err)
	}
	events := make([]*model.Event, 0, len(resp.GetEvents()))
	for _, e := range resp.GetEvents() {
		events = append(events, mapEvent(e))
	}
	return &model.EventPage{
		Events:   events,
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// GetTicketsByUser is the resolver for the getTicketsByUser field.
func (r *queryResolver) GetTicketsByUser(ctx context.Context, userID string) ([]*model.Ticket, error) {
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("authentication required")
	}
	if claims.Role != "admin" && claims.UserID != userID {
		return nil, gqlerror.Errorf("cannot access tickets for another user")
	}
	resp, err := r.Clients.Ticket.GetTicketsByUser(ctx, &ticketv1.GetTicketsByUserRequest{UserId: userID})
	if err != nil {
		return nil, grpcError(err)
	}
	tickets := make([]*model.Ticket, 0, len(resp.GetTickets()))
	for _, t := range resp.GetTickets() {
		tickets = append(tickets, mapTicket(t))
	}
	return tickets, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func derefInt(p *int, def int) int {
	if p == nil {
		return def
	}
	return *p
}

func derefString(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

func grpcError(err error) error {
	if st, ok := status.FromError(err); ok {
		switch st.Code() {
		case codes.InvalidArgument, codes.AlreadyExists, codes.NotFound, codes.FailedPrecondition, codes.PermissionDenied:
			return gqlerror.Errorf("%s", st.Message())
		default:
			return gqlerror.Errorf("service error: %s", st.Message())
		}
	}
	return err
}
