// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateEventInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Location    string `json:"location"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	Capacity    int    `json:"capacity"`
}

type Event struct {
	ID             string `json:"id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Location       string `json:"location"`
	StartTime      string `json:"startTime"`
	EndTime        string `json:"endTime"`
	Capacity       int    `json:"capacity"`
	AvailableSeats int    `json:"availableSeats"`
	Status         string `json:"status"`
	CreatedBy      string `json:"createdBy"`
	CreatedAt      string `json:"createdAt"`
}

type EventPage struct {
	Events   []*Event `json:"events"`
	Total    int      `json:"total"`
	Page     int      `json:"page"`
	PageSize int      `json:"pageSize"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Ticket struct {
	ID         string `json:"id"`
	UserID     string `json:"userId"`
	EventID    string `json:"eventId"`
	Status     string `json:"status"`
	TicketCode string `json:"ticketCode"`
	CreatedAt  string `json:"createdAt"`
}

type UpdateProfileInput struct {
	Name string `json:"name"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}
